CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    reservation_uuid VARCHAR(64) NOT NULL UNIQUE,
    apartment_id VARCHAR(64) NOT NULL,
    source VARCHAR(20) NOT NULL DEFAULT 'manual',
    external_uid VARCHAR(191) NULL,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'reserved',
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    customer_first_name VARCHAR(120) NULL,
    customer_last_name VARCHAR(120) NULL,
    customer_email VARCHAR(190) NULL,
    customer_phone VARCHAR(64) NULL,
    customer_country VARCHAR(90) NULL,
    customer_document VARCHAR(120) NULL,
    adults SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    children SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    notes TEXT NULL,
    price_total DECIMAL(12,2) NULL,
    price_currency VARCHAR(12) NULL,
    tax_amount DECIMAL(12,2) NULL,
    cleaning_fee DECIMAL(12,2) NULL,
    discount_amount DECIMAL(12,2) NULL,
    payment_status VARCHAR(40) NULL,
    payment_method VARCHAR(80) NULL,
    booking_channel VARCHAR(80) NULL,
    readonly_flag TINYINT(1) NOT NULL DEFAULT 0,
    archived_flag TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_dates (start_date, end_date),
    INDEX idx_apartment (apartment_id),
    INDEX idx_source (source),
    INDEX idx_external_uid (external_uid)
);

CREATE TABLE IF NOT EXISTS reservation_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    reservation_uuid VARCHAR(64) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    payload_json LONGTEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_reservation_uuid (reservation_uuid),
    INDEX idx_event_type (event_type)
);
